spring.application.name=editorialSpringboot

spring.datasource.url=jdbc:postgresql://localhost:5432/editorial
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.default_schema=prestamolibros

# JWT
app.jwt.secret=0123456789abcdef0123456789abcdef
app.jwt.access-minutes=15

# Seed user (dev) - opcional pero recomendado para no perder tiempo
app.security.seed.enabled=true
app.security.seed.username=admin
app.security.seed.password=admin123

